### ISSUE TITLE
Curse/Twitch Error?

### ISSUE THREAD

**Issue by hasezoey** [mrmakeit/OCJS#16]
i Dont know why, but i cant find the mod in a Curse/Twitch 1.12.2 modpack...
on the website i see that there is a 1.12.2 version, but the launcher cant find it.
((The only Version.) 0.5.1)
Is it an Curse/Twitch Error, or is it wrong tagged on the site?

**Comment by Techokami** [comment]
I don't think the author has published it on Curse yet. Until he does so, either he has to go through a process to get builds of the mod added to a special whitelist, or you can't make a pack with this mod included.

It's hot garbage, I know. I want to add some things to a pack my friend made but because they aren't on Curse or whitelisted, and he wanted to use Curse for convenience, I just can't. Heck I've had the whitelist fail on me! The TTS components of Computronics are supposed to be whitelisted, but I've gotten rejection messages from admins who refuse to communicate with me about false positives.

**Comment by hasezoey** [comment]
GitHub Patron Link: https://github.com/mrmakeit/OCJS#support
On this Patreon stands "Feel free to go grab the current alpha from either the releases page, or from CurseForge."
to this Curse Link: https://minecraft.curseforge.com/projects/ocjs

so it is on Cruse, official

**Comment by Techokami** [comment]
OH I see now. It's listed as an alpha version, which means it won't show up in the Twitch launcher. It has to be a beta or release to make it properly be detected.

**Comment by hasezoey** [comment]
Oh, yeah i see it yet too, alpha not shown, beta is shown,

So mainly the question is answered, i close it now ^^
