### ISSUE TITLE
computer.direct() is not a function

### ISSUE THREAD

**Issue by hasezoey** [mrmakeit/OCJS#43]
`computer.direct();`

**Comment by mrmakeit** [comment]
Nope, not anymore.  Direct mode made lua code execute on the main thread instead of the machine thread. Setting the architecture in direct mode only makes sense in a stack based language.  Since JavaScript is event based, and executes invoke calls asynchronously, the `computer.direct()` call didn't add any value, can't be used with the sandbox library around nashorn (it uses threads to maintain cpu usage), and could potentially be abused to break the main thread. 
As such, i have removed it for now.  It may end up making sense to include it once native libs are added, but not while using nashorn.

**Comment by hasezoey** [comment]
only testet it because it stands in the wiki to execute it in the world

**Comment by mrmakeit** [comment]
Thought I had removed it from the wiki.  Thanks for the heads up.
